name: submit-contest
on: 
  push:
    branches:
      - qa/**
      - fa22/**

jobs:
  test-and-submit-student-solution:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "adopt"
          cache: maven

      - name: Run Unit Tests
        id: run_unit_tests
        run: ./.github/workflows/test_and_upload.sh
        shell: bash

      - name: Sanity Check Results
        run: echo "${{ steps.run_unit_tests.outputs.results }}"

      - name: Upload Results
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "${{ secrets.WEBHOOK_URL }}"
          webhook_secret: "${{ secrets.WEBHOOK_SECRET }}"
          data: '{ "user": "${{ github.actor }}", "results": ${{ steps.run_unit_tests.outputs.results }} }'


